DROP USER IF EXISTS app;

CREATE USER app WITH CREATEDB CREATEROLE SUPERUSER LOGIN PASSWORD 'app';

DROP DATABASE IF EXISTS commons;

CREATE DATABASE commons WITH OWNER postgres;
GRANT ALL PRIVILEGES ON DATABASE commons TO app;